name: "Spotbugs"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '20'
          cache: 'gradle'

      - name: Main Spotbugs
        run: ./gradlew spotbugsMain

      - name: Test Spotbugs
        run: ./gradlew spotbugsTest