 name: "Tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - { operating-system: 'ubuntu-latest', java-version: '19' }
          - { operating-system: 'ubuntu-latest', java-version: '21' }

    runs-on: ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'

      - name: Run tests with gradle wrapper
        run: ./gradlew test